name: SimpleFiturePlugin
version: 1.2 BETA
main: com.saryu.saryuplugin.Main
api-version: "1.21"
load: POSTWORLD
author: Sahur
description: ยง4PROTOTYPE MADE BY SAHUR
depend: [Multiverse-Core]
commands:
  duel:
    description: Duel another player
    usage: /duel <player|accept|cancel>
  pvp:
    description: Toggle PvP
  gacha:
    description: Gacha command
  smfp:
    description: SimpleFiture main command
    usage: /smfp reload
  test:
    description: Test command
